### ISSUE TITLE
Investigate github-todos

### ISSUE THREAD

**Issue by ghost** [meteor-gazelle/meteor-gazelle#100]
There is a project that creates issues from todo comments, worth looking into https://github.com/naholyr/github-todos

**Comment by thomwiggers** [comment]
I'm not entirely sure this is worth it as you'd need to go through them all over again to assign milestones etc.

**Comment by ghost** [comment]
I think it'll be useful as long as we check the issues after it runs.

**Comment by jimrollenhagen** [comment]
I don't like making issues for TODOs, it's duplication. Also, many TODOs are not immediately actionable and they could just pile up. For example: `// TODO remove this hack when X is sorted out.`

If someone wants to work on TODO things, `grep -R TODO .` is pretty easy.

**Comment by ghost** [comment]
Alright guys. Closing this.
