### ISSUE TITLE
Rename internal packages meteor-gazelle-somepackage

### ISSUE THREAD

**Issue by ghost** [meteor-gazelle/meteor-gazelle#102]

**Comment by jimrollenhagen** [comment]
Convention appears to be (for example) `gazelle:users` in the meteor community. I think I'd rather do something like that.

**Comment by ghost** [comment]
@jimrollenhagen I've seen packages which use the full project name, in our case "meteor-gazelle" rather than "gazelle". As for dash vs semicolon there isn't consistency there that I've seen between package authors. "meteor-gazelle:something" vs "meteor-gazelle-something". I like the semi colon personally.

**Comment by ghost** [comment]
I don't have much of an opinion on this, but "meteor-gazelle:package" sounds nice.

**Comment by ahaym** [comment]
pull request #121 addresses this issue.
