### ISSUE TITLE
Consider using ES6/ES7 in meteor

### ISSUE THREAD

**Issue by salas-wcd** [meteor-gazelle/meteor-gazelle#103]
Looking at the [custom merge function](https://github.com/meteor-gazelle/meteor-gazelle/blob/master/packages/gazelle-schema/gazelleSchema.js#L4-L15) or the [bunch of inheritance with the prototype chain](https://github.com/meteor-gazelle/meteor-gazelle/blob/master/packages/gazelle-schema/gazelleSchema.js#L28) it may be a right idea to write using ES6/ ES7 syntax.

In my case it was a real improvement in term of readability and reviewing.

See https://medium.com/@dferber90/es6-in-meteor-5e088c998e4a for infos about es6 in meteor.

**Comment by salas-wcd** [comment]
**Pros**
- arrow function : https://leanpub.com/exploring-es6/read#ch_arrow-functions
- destructuring : https://leanpub.com/exploring-es6/read#ch_destructuring
- promises : while meteor uses fibers for async on server they can still be usefull in client side https://leanpub.com/exploring-es6/read#ch_promises
- templates litterals : https://leanpub.com/exploring-es6/read#ch_template-literals
- spread : https://leanpub.com/exploring-es6/read#sec_spread-operator
- rest : https://leanpub.com/exploring-es6/read#sec_rest-parameters

**Cons**
- need to add meteor-babel (previously 6to5)
- need to handle sourcemap

**Comment by sneakysneakysneaky** [comment]
[ES2015 (ES6) will be officially supported in Meteor v1.2](http://info.meteor.com/blog/whats-coming-in-meteor-12-and-beyond). The team has opted to wait for official support rather than rely on third party packages.

**Comment by salas-wcd** [comment]
Seems legit ;)
I'm quite new in meteor world. You would have y help making transition to ES6 once 1.2, I do this since 5 month now :(
