### ISSUE TITLE
Consider using Phabricator as primary task for this project

### ISSUE THREAD

**Issue by salas-wcd** [meteor-gazelle/meteor-gazelle#105]
While **github is a nice platform** for opensource projects, I have **some concerns** using it for gazelle. Let me explain:
- first **we dont host it** and thus it can be taken down with some **DCMA complains** like it was for https://github.com/rover12421/JetbrainsPatchKeygen. More and more borderline projects had been taken down by Github lasts month and if the code is shared upon all dev, the issues isn't.
- they're is **no way to restrain the visibility** of an issue to a certain group of people which can be problematic to report security issue
- the **management of issues** (with tags only) is **nice for small** but can be a nightmare for some projects. **It is lacking some workboard** in order to classify the task better (like your usage of trello)
- github is **not the best convivial plateform** : I mean having a nice meme like this http://imgur.com/0I8NGqD or so on is so much encouraging and funny than same sentence without meme while reviewing and thinks like badges are so good to motivates people.
- it miss some nice feature : like mockup reviewing, voting tools

Upon the past years I discovered **phabricator**, a tool written by **facebook** then opensourced and used by big project (like FreeBsd or WMF), which as some advantages:
- **nice organisation of tasks** : https://secure.phabricator.com/project/view/543/
- possibility of **sprint** using a plugin : https://phabricator.wikimedia.org/project/sprint/burn/1354/
- a nice tool for **reviewing** that can be really productive with the command line tools : https://secure.phabricator.com/D13635 (I m going to details this later)
- a tool for **reviewing mockup** : https://secure.phabricator.com/M14/16/
- a **bunch of meme**, including a meme generator : https://secure.phabricator.com/T9035#129366
- **badges** : https://secure.phabricator.com/p/epriestley/
- a **CI and Continuous deployment** :  screenshot from haskell phabricator instance http://i.imgur.com/XH6O7kc.png
- a nicer wiki
- can host repository and mirror it on github or can work on a github hosted repository 
- a lot of other nice to have features (like realtime notification, vote, quora like best-answering system, irc bot)

The **workflow is a little bit different** from github's one so let me explain it:
- you **dev some nice feature** on your local machine and put it on a **local branch** like 'feature-xxx'
- you **may want to save your branch on server too** by pushing it but it wont be tracked since you configured to only track like master. But it allow you to pull from an other computer to keep working
- you **commit your work** using git
- once your works is working you run `arc diff` ! Arc is arcanist the command line from phabricator which is easy to install in linux mac or windows ! This will **create a new revision** (consider this like a new PR in github and a first diff in this revision)
- `arc diff` will triger `arc unit` and `arc lint` that basically will **execute unit tests and lint on local machine** for **changed files only** (will solve slow test on meteor) before ever sending diff. If some linting or unit test failed, they **will ask you for an excuse** while creating diff (like non related stuff) and the lint issue will be inline commented in the diff. The coverage will also display on the diff if configured  
- then **someone review your code** and point out all the missing stuff and bad practices
- you **update your code on your local branch** and `arc diff` again ! This time it will not create a new ref but update the existing one with a new diff.
- when all is ok, one reviewer can `arc land xxxxx`  where xxxxx is the revison name. This will **close the revision and make a single commit** with all change in.

What about hosting our phabricator instance, opening it to public.

**Comment by salas-wcd** [comment]
Forgot to say that Im proficient with phabricator installation so I m gonna help if we choose to host our code.

**Comment by aarocka** [comment]
It is probably a good idea to have backup git hosting incase github gives us a dmca request. One thing to keep in mind is that this project uses travis-ci. If we switch away from github we loose free use of travis-ci. You would also loose access to very useful tools such as coveralls and code climate. This is something to keep in mind.

**Comment by ghost** [comment]
I highly doubt anything along those lines would happen. The code is backed up and there's always gitlab as an alternative. Not to mention Gazelle has been on Github for 2 years now I think. 

Github works well, it's simple and the lowest common denominator amongst developers. Let's not over complicate things. 

Closing this issue.
