### ISSUE TITLE
Consider using a time-series database

### ISSUE THREAD

**Issue by salas-wcd** [meteor-gazelle/meteor-gazelle#107]
Some context here: in our (no more info) highly modified version of gazelle, we end up planning modifying ocelot and gazelle to make use of a time series database : namely [influxDB](https://influxdb.com/index.html).

Basically, this separation between data in NoSQL (Mongo visibly here, our choice was a ACID GraphDB namely OrientDB) and time series in Influx would allow some powerful analysis and feature (like dont leeching more than 120% of needed peers : if someone can download at speed 100 kB/s, and if the next 7 peers can leech at 120 kB/s dont give a list of 100 peers by default, whats make harder for gov to track seeders).

WDYT

**Comment by ghost** [comment]
Thanks for the suggestion. We're going to stick with Mongo and if needed introduce a micro service for SQL if needed for better handling torrent data. 

Closing.
