### ISSUE TITLE
Generic Revision History

### ISSUE THREAD

**Issue by ghost** [meteor-gazelle/meteor-gazelle#116]
We need a way to handle a generic revision history, for things such as wiki, artists, etc.

**Comment by ghost** [comment]
Ideas on how to implemention. 

Bind some behavior to a collection so when an update operation runs a revision is automatically made. You should be able to specify which fields in the document you want to track.

**Comment by c-p-b** [comment]
This should include a mechanism for isolating and displaying the diff. A cursory glance reveals several libraries already available, notably including https://github.com/kpdecker/jsdiff

Perhaps there is a simple but elegant way to store only the diffs and back apply them when necessary, a-la git.

**Comment by borghunter-wcd** [comment]
This seems neat, but also heavy. (and javaaaa) http://javers.org/

On a much simpler level, Meteor core's [`observeChanges`](http://docs.meteor.com/#/full/observe_changes) on collections can pick up diffs and store them.

**Comment by ghost** [comment]
These two packages do what we're looking for https://github.com/todda00/meteor-collection-revisions/ and https://github.com/jeanfredrik/meteor-temporal/ they should both be reviewed and one of them possibly chosen to do this. 

We may or may not still want to write some wrapper helper methods for our purposes...

**Comment by daveynight** [comment]
OK, after tinkering for a little while I'm going with meteor-collection-revisions. "Option to ignore (not save) certain fields within your documents" is on the wish list, so at some point I might try to pick up enough CoffeeScript to add that feature.
