### ISSUE TITLE
Support Themes

### ISSUE THREAD

**Issue by sneakysneakysneaky** [meteor-gazelle/meteor-gazelle#126]
Gazelle will continue to support themes. Users will be allowed to select a theme from their profile settings to personalize the basic look & feel of the site.

Some issues that need to be addressed:
1. Scope what a theme is from a technical standpoint:
   - Is it an entire stylesheet?
   - Is it a Meteor package? Or some other kind of module?
   - Is it a stylesheet that overrides a core stylesheet? And if so, what elements are considered "core" styles, & what elements are considered "themable"?
2. Currently, the Meteor build process concats all stylesheets together. Determine how to control this step & separate stylesheets as we see fit.
3. Determine how to inject stylesheets into the DOM at runtime using Meteor.

**Comment by thomwiggers** [comment]
I think stylesheets being meteor packages might be a bit too much, as this will make it impossible for users to run their own stylesheets like they can now: by just inserting a CSS url.

**Comment by rhomes-wcd** [comment]
@ajax-wcd Speaking to you a week or so ago I thought you had mentioned we wouldnt be supporting this on the rewrite?

**Comment by ghost** [comment]
@sneakysneakysneaky @thomwiggers @rhomes-wcd Officially we will only support one or two stylesheets, most likely a light and dark variant. 

However we will be introducing new tools to replace/coexist with the "Laboratory" forum where users can share their custom stylesheets and choose to apply stylesheets created by others.

**Comment by sneakysneakysneaky** [comment]
If the site is going to support more than one stylesheet, either created by us or by third parties, this issue applies.

**Comment by rhomes-wcd** [comment]
@sneakysneakysneaky Indeed, just wanted to clarify.

**Comment by salas-wcd** [comment]
if we organise our rule using https://smacss.com/book/categorizing, we could still have one code pro module and one theme that will overwrite above rules ??

**Comment by sneakysneakysneaky** [comment]
We're using BEM, not SMACSS. But i believe the principle is the same.

I fear the concept of a core stylesheet. It feels very much like a legacy concept to me. Runs the risk of too much of a footprint. Rules will get created in the core stylesheet just to be overridden & never used in the theme stylesheet. Even if we keep the core stylesheet to a bare minimum, some styles will inevitably be overridden into oblivion.

I am much more in favor of theme = stylesheet. Keep markup as semantic as possible. Let authors style it how they will. The code for the default theme will be open source; authors can use that as a base.
