### ISSUE TITLE
Internationalization (i18n)

### ISSUE THREAD

**Issue by borghunter-wcd** [meteor-gazelle/meteor-gazelle#134]
This should be baked into core, every string, everywhere. 

Library tbd, will post suggestions.

http://meteorpedia.com/read/i18n

**Comment by borghunter-wcd** [comment]
Powerful/New school: https://atmospherejs.com/gadicohen/messageformat
Simple/Old school: https://atmospherejs.com/tap/i18n/

The issue with the former, is that it doesn't seem to work with packages super well (yet). Ideally each package would be namespaced by default, but that doesn't seem to be the case. messageformat also seems to store the translations in the db, boo.

**Comment by thomwiggers** [comment]
about messageFormat: 

```
Note: Each translation string must have a unique key. In the above example, trans_string is the key.
```

Wow, that's incredibly annoying.

The other package, i18n, is also awful imo, because you _also_ need unique keys for everything and have to keep a translation file updated all the time.

Why can't it just use gettext/a gettext like approach.

**Comment by borghunter-wcd** [comment]
Yeah, there doesn't seem to be a meteor specific package for gettext. 
This looks pretty decent as a general js solution.
https://slexaxton.github.io/Jed/

**Comment by ghost** [comment]
@thomwiggers why don't you like unique keys? Don't most i18n packages require that?

**Comment by thomwiggers** [comment]
Everything I've worked with (aka gettext in Django, but also in php) roughly works like this:

Source file:

```
{{ trans 'This gets translated' }}
```

nl_NL.po

```
msgid "This gets translated"
msgstr "Dit wordt vertaald"
```

So this means you don't need to hassle with keeping things synchronous, and if you don't translate a string it'll just display the original language.

Adding identifiers to strings is supported iirc, but that's mostly to support stuff where there are words that are the same in one language (Dutch: "bank", English: "bank" or "sofa")

**Comment by guitarman0831** [comment]
In your example, is msgid not the unique key for the message?

**Comment by thomwiggers** [comment]
Yes, but it's also the English text. I don't see that in these meteor packages. 

On 6 August 2015 19:08:53 CEST, Jason notifications@github.com wrote:

> In your example, is msgid not the unique key for the message?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/meteor-gazelle/meteor-gazelle/issues/134#issuecomment-128446173

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by borghunter-wcd** [comment]
I like unique keys, since using the english text is exactly the same, or worse, and will become very apparent when you make a typo or want to change said english text. 

When that happens you have two options:
1. Change the english text used in the templates (essentially the "key"), then go through every .po file and change the text there, and make sure all translators have up to date keys, or...
2. You leave the template text asis and create a new english .po file to translate the "shitty english" to "good english".

**Comment by thomwiggers** [comment]
Gettext fixes your problem by allowing for 'fuzzy' translations, where it does a 'close enough' guess. Often you only need to briefly review them and you're done.

Tooling for gettext is also really mature. Stuff like transifex etc..

**Comment by jimrollenhagen** [comment]
gettext ftw. Jed seems... overkill, but I think it should work.

Besides the "how do things get translated" bits, we're going to need some infrastructure to generate .po files, make it easy for people to translate things, etc. If the translation process is "create and PR a .po file", nobody will do it.

Not everything here will apply, but OpenStack has a lot of infra here we may be able to crib from:
- https://wiki.openstack.org/wiki/Translations
- https://wiki.openstack.org/wiki/Translations/Infrastructure

The thing I really like about the way OpenStack does translation, is it makes it ridiculously easy for developers. Just `_("wrap your string")` and it will get picked up as a translation and pushed into Transifex. Updates to the English form are managed by marking line numbers and whatnot, AIUI. Translators can do their thing directly on Transifex's website, and then a periodic job pulls translations from Transifex and proposes a patch for review.

All of that said, I don't know that this is the best use of our time right now. I would like to figure it out so we can start marking strings or whatever, but the rest of the process might take some time.

**Comment by ghost** [comment]
I'm in favor of revisiting this issue in the future as it is low priority. We can organize an internalization effort as well to go along side this.
