### ISSUE TITLE
Design a meta-model for groups/torrents/etc

### ISSUE THREAD

**Issue by thomwiggers** [meteor-gazelle/meteor-gazelle#137]
We need some kind of meta-model on which we can map the artist / album / torrent structure. This model needs to be flexible enough to allow for other types of content, such as e-learning, e-books and software.

This is kind of a hard problem.

**Comment by thomwiggers** [comment]
Some doodling got me this. (It's an ORM diagram)
tl;dr: torrents are a member of one group. Groups can contain either torrents xor other groups. Each group can only be member of one super group. Groups can be specialised (the arrows): these specialisations contain the extra information needed for that 'specialty'.

![orm](https://cloud.githubusercontent.com/assets/974662/9110522/a7bed9ea-3c3e-11e5-9909-a39b98c4f728.png)

**Comment by ghost** [comment]
It says examples of specialisations. Is that why we are using words like album and artist?

**Comment by thomwiggers** [comment]
Yeah, you could also fill in other things there. It's kinda hard to express in the diagram, but an album in this diagram is a group which contains release groups. But in the 'general' sense these are all just 'group's.

**Comment by sneakysneakysneaky** [comment]
Great stuff, @thomwiggers.

What about if an album has multiple contributing artists?

**Comment by ghost** [comment]
That is one of the issues I was facing @sneakysneakysneaky. My thought was to consider a table that would have 3-tuples. Release ID, Artist ID (fr lack of a better word), Role ID (so we can assign what role that artist had). 

Edit: my large concern in this is that it lends itself to some duplication of data, hence if one release has 10 artists now the release ID is duplicated 10 times... Also role IDs can only be created from an admin user and these would probably be selected from a drop down.

**Comment by Malvar** [comment]
Just as an idea, another project I was working on would use the object _id to describe the relationship that the object contains. So you would have a single table of objects that look like this:

``` javascript
{
    "_id" : "<maskable#>_<owner_id>_<owned_id>",
    "data" : { /* meta data object that contains specific info about the relationship */ }
}
```

Since the database was setup where we could bitmask the initial part of the _id, so creating queries became easy. Example:

> Artist : 1
> Album : 2
> Book : 4
> Torrent : 8
> User : 16

So an object about a torrent _id:321 owned by User _id:123 would look like this:

``` javascript
{
    "_id" : "24_123_321",
    "data" : { /* ... */ }
}
```

And an album #789 that has 2 artists ( _ids = 'abc' and 'xyz' ) associated would have two objects in the database

``` javascript
{
    "_id" : "3_abc_789",
    "data" : { /* ... */ }
}
{
    "_id" : "3_xyz_789",
    "data" : { /* ... */ }
}
```

**Comment by ghost** [comment]
Here is a schema I started working on awhile ago. Food for thought. 

These are three articles I found quite useful
http://blog.mongodb.org/post/87200945828/6-rules-of-thumb-for-mongodb-schema-design-part-1
http://blog.mongodb.org/post/87892923503/6-rules-of-thumb-for-mongodb-schema-design-part-2
http://blog.mongodb.org/post/88473035333/6-rules-of-thumb-for-mongodb-schema-design-part-3

The 'contents' field of Schemas.torrentGroup in this case would be Schemas.music.

``` javascript

Schemas.torrent = new SimpleSchema({
  groupId: SchemaAutoFields.id('group'),
  createdAt: SchemaAutoFields.createdAt(),
  createdBy: SchemaAutoFields.createdBy(),
  leechType: SchemaAutoFields.leechType('torrent')
});

Schemas.torrentGroup = new SimpleSchema({
  type: {
    type: String,
    label: 'The group\'s type',
    allowedValues: function () {
      return [ 'Music', 'E-Book', 'Comic' ];
    },
    index: true
  },
  createdAt: SchemaAutoFields.createdAt(),
  createdBy: SchemaAutoFields.createdBy(),
  title: SchemaAutoFields.name('group', false),
  images: SchemaAutoFields.images('group'),
  description: SchemaAutoFields.description('group', true),
  tags: SchemaAutoFields.tags('group'),
  leechType: SchemaAutoFields.leechType('group'),
  collages: {
    type: [new SimpleSchema({
      id: SchemaAutoFields.id('collage'),
      name: SchemaAutoFields.name('collage', false)
    })],
    label: 'The collages that this group belongs to',
    optional: true
  },
  requests: {
    type: [new SimpleSchema({
      requests: SchemaAutoFields.id('request'),
      name: SchemaAutoFields.name('request', false)
    })],
    label: 'The requests that this group belongs to',
    optional: true
  },
  torrents: {
    type: [String],
    label: 'The ids of torrents in this group',
    optional: true
  },
  contents: {
    type: Object,
    optional: true,
    blackbox: true
  }
});

Schemas.musicTorrent = new SimpleSchema({
  id: SchemaAutoFields.id('torrent'),
  format: {
    type: String,
    label: 'The torrent\'s format',
    allowedValues: function () {
      return [ 'MP3', 'FLAC' ];
    }
  },
  bitrate: {
    type: String,
    label: 'The torrent\'s bitrate',
    allowedValues: function () {
      return [ '320', 'V0' ];
    }
  }

});

Schemas.musicRelease = new SimpleSchema({
  id: SchemaAutoFields.id('release'),
  releaseTitle: SchemaAutoFields.name('release', true),
  releaseYear: SchemaAutoFields.year('release'),
  label: {
    type: new SimpleSchema({
      id: SchemaAutoFields.id('label'),
      name: SchemaAutoFields.name('label')
    }),
    label: 'The labels this group belongs to',
    index: true
  },
  torrents: {
    type: [Schemas.musicTorrent],
    label: 'The torrents under this release',
    index: true
  }
});

Schemas.musicEdition = new SimpleSchema({
  id: SchemaAutoFields.id('edition'),
  editionYear: SchemaAutoFields.year('edition'),
  editionName: SchemaAutoFields.name('edition', true),
  editionMedium: {
    type: String,
    label: 'The edition\'s medium',
    allowedValues: function () {
      return [ 'CD', 'Vinyl', 'WEB' ];
    }
  },
  releases: {
    type: [Schemas.musicRelease],
    label: 'The releases under this group'
  }
});

Schemas.music = new SimpleSchema({
  artists: {
    type: [new SimpleSchema({
      artistType: {
        type: String,
        label: 'The artist\'s type',
        allowedValues: function () {
          return [ 'Musician', 'Band', 'Composer' ];
        }
      },
      id: SchemaAutoFields.id('artist', false),
      name: SchemaAutoFields.name('artist'),
      createdAt: SchemaAutoFields.createdAt(),
      createdBy: SchemaAutoFields.createdBy()
    })],
    label: 'The artists that contributed to this music',
    index: true
  },
  releaseType: {
    type: String,
    label: 'The music\'s release type',
    allowedValues: function () {
      return [ 'Album', 'EP', 'Soundtrack' ];
    }
  },
  editions: {
    type: [Schemas.musicEdition],
    label: 'The editions in this group'
  }
});

Schemas.artist = new SimpleSchema({
  name: SchemaAutoFields.name('artist'),
  description: SchemaAutoFields.description('artist', true),
  images: SchemaAutoFields.images('artist'),
  createdAt: SchemaAutoFields.createdAt(),
  createdBy: SchemaAutoFields.createdBy(),
  groups: {
    type: [String],
    label: 'The groups this artist belongs to',
    optional: true,
    index: true
  }
});

```

**Comment by TheDevKing** [comment]
I don't know if it's a practical for this framework, but I've been thinking about this for a while and my mind keeps going back to how MusicBrainz is structured. It really seems ideal, even for general purpose content. I don't think much would have to be changed, so long as the schema allowed for the creation of new "content types".

That said, I haven't even begun to wrap my mind around how this would work in practice.

**Comment by TheDevKing** [comment]
[Schema.org](http://schema.org/) is a fantastic reference. [CreativeWork](http://schema.org/CreativeWork) really seems to describe the most appropriate vocabulary for a project like this. I think these terms are general enough to apply to most, if not all, use cases for this framework.

To use the example from above of multiple Artists on a single Album, the [mainEntity](http://schema.org/mainEntity), which only expect 'person' as the type) could be checked for. If it was null, then "Various Artists" could be used. For albums featuring multiple artists, but still under a primary artist,  the mainEntity would be defined as the primary artist and others would be listed as a [contributor](http://schema.org/contributor). The contributer property expects either a person or an organization and the mainEntity property will accept any "thing", which, appropriately, can be just about anything. A [MusicGroup](http://schema.org/MusicGroup) is a type of organization.

I think mainEntity is more appropriate than [creator](http://schema.org/creator) as a primary artist, but I'm not sure.

Perhaps I'm overlooking something or am misunderstanding the problem, but wouldn't use of Schema.org solve this whole thing?

**Comment by c-p-b** [comment]
I've been working on this issue and reading input of everyone on this thread and recent interest in Astronomy. Going to put together a draft to be posted here for review by end of next week (8/23). Ping me as AmbientNoise on IRC if you would like to discuss.

EDIT 8/23: Still working on this. Expect a PR in the next few days.
