### ISSUE TITLE
Chronological vs. Hierarchical forum sorting 

### ISSUE THREAD

**Issue by ghost** [meteor-gazelle/meteor-gazelle#139]
Proposed idea:

```
11:44   Salas   Upon my reflexion rewriting gaelle before meteor-gazelle i had the idea that while creating a new thread one could choose between normal (chronological thread) or hierachical (redis like)
11:50   Salas   we suppot both
11:50   Salas   but on creation author can chose betwwen the two organisation mode
```

Pretty much, it's suggested that the thread author has the option to choose between chronological (the way it is now), or hierarchical (Reddit-style).

**Comment by salas-wcd** [comment]
The concept comes upon threads in technologies or lounge asking for review or really open to different answers (like "best laptop of 2015" or the "headphone thread") where it would be more clear if it was hierarchical.

The proposal is to let thread creator chose one configuration on creation, not replacing all currrent system with proposal.

**Comment by salas-wcd** [comment]
Moreover that can be a flexible alternative on poll.  The current poll is immutable so if a genious non considered idea comes we have to close the thread and the poll and open a new thread and poll. 

That is nice for binary poll like "will we make a freelech event for tracker birthday" but not for multi answer proposal like "what about adding 7z as supported content for game ups".  For that,  hierarchical thread with upvoting is perfect.

**Comment by ghost** [comment]
@salas-wcd We have ideas on polls thoughtout pretty well @felix1429 and/or @guitarman0831 to dig up that information and create issues. (It's somewhere on Trello). 

The reddit style threads are an interesting idea but it is low priority, we should be focusing on getting the forums functioning in the "classic" sense. Reddit style is something we can consider in the future and we should definitely code our fourm in such a way that it's flexible to add reddit style , I suggest making a new issue or rewording this one.

**Comment by ghost** [comment]
@ajax-wcd @salas-wcd #140

**Comment by thomwiggers** [comment]
Reddit-style comments have been suggested in the suggestion forum multiple times now, but has been shot down multiple times. 

I think we answered this question: for now we're doing classic forums. We can revisit this suggestion further down the road.

If anyone disagrees, feel free to reopen the issue, of course.
