### ISSUE TITLE
Specs seem to reflect a more narrow goal than the Readme

### ISSUE THREAD

**Issue by TheDevKing** [meteor-gazelle/meteor-gazelle#142]
"Gazelle is a web framework geared towards private BitTorrent trackers."
In my understanding, this sounds like the goal is broad applicability to all sorts of types of trackers. The specs so far seem to narrow the scope of the project to music centered trackers specifically. For example, [homepage.md](https://github.com/meteor-gazelle/meteor-gazelle/blob/master/doc/specs/homepage.md) makes specific mention of "Albums".

Of course modification would be possible down the line to adapt to whatever is needed, but I think there are clear benefits to developing this as a content-neutral framework. The first and foremost is that it makes collaboration easier. If there's several trackers with a variety of content, their codebases can remain the same. If they fix a bug or improve a feature they won't have to worry as much about the changes they've had to make to fit the framework to their content. I know this isn't a huge issue, but I think reducing the barrier to contribution is important.

Constraining development to certain assumptions makes it easy to overlook potential useful alternatives. An admittedly iffy example of this is assuming a single image represents a torrent group. This example is even more iffy given the fact that (I think) Gazelle has resolved this by allowing multiple images in the form of alternatives. My point is that the utility of multiple images per group is the type of thing that's easy to overlook when you're only focused on a single use case. Taking the broad view makes it easier to see that a single image is not appropriate in all cases. Ultimately, the recognition that it's not appropriate in all cases often necessitates it being developed as more robust feature that can be configured in a variety of ways.

Additional configurability is something that's often useful and can be leveraged into new features that may or may not be applicable to implementations of the framework that previously didn't take advantage of the feature.

I understand that a more general scope adds more work, but I think it's worth it in the long run and would ultimately result in a better piece of software. If this change in the approach in development of this project is going to be made at all, I think it's better to make it sooner than later.

To start this change off, I would suggest changing references to "Artists" and "Albums" to something like "Groups" and "Items", respectively. I don't know what the best terms to use are, but something that's generally applicable and describes their behavior/function. I'm not suggesting that these terms be part of the UI, but that it's how things are referred to in code. Configuration and/or localization could be used to apply more appropriate labels in the UI to these otherwise very general terms.

My main concern isn't that of the ease of portability or even the words used, but the mentality of the development itself.

**Comment by sneakysneakysneaky** [comment]
Thank you for your comments. The points you have raised are definitely understood by the team. There is an ongoing conversation in #137 about how to organize the data without overspecializing.

I'm afraid this has been overlooked in some of the specs--the homepage spec being a good example.

**Comment by ghost** [comment]
@TheDevKing All very good points.

**Comment by thomwiggers** [comment]
This needs fixing, so I've refiled this as a bug. However, we should first tackle #137.

**Comment by jimrollenhagen** [comment]
Fantastic commentary :+1:

I've been pushing for this mindset as well, but maybe not hard enough.

**Comment by jimrollenhagen** [comment]
@thomwiggers is there really anything to do here? I remember seeing folks fixing some of the specs... but I don't think we have a solid way to say "this is done" right now, and this issue will be forever open.

**Comment by thomwiggers** [comment]
I think we can close the 'bug' part of this issue if the pointed out problems in the OP are fixed, and the technical stuff will probably be mostly addressed by #137.

The state of mind is indeed an ongoing concern, but I don't think we need this issue to stay open for that.

**Comment by ghost** [comment]
Closing this issue and opening an issue to create a general list of terms we are using for content on the site. For example rather than 'artist' call it a 'content creator'. I believe @Malvar started on a glossary already...
