### ISSUE TITLE
Authorization checkpoint

### ISSUE THREAD

**Issue by lawnmowerwcd** [meteor-gazelle/meteor-gazelle#143]
For historic reasons authorization code has been scattered throughout the whole application because it was added after the actual program logic. Adding authorization to the application design is preferable.

To centralize authorization a checkpoint can be introduced that
- checks permissions
- logs permission requests
- performs the requested action

Pros for this approach are:
- cleaner code: no permission checks in unrelated code
- single point of failure: accidently checking for different permissions when accessing the same action not possible
- easy to check/verify security policies: all actions that require a permission are registered at one place. Very easy to check if any action requiring a specific permission is registered and has the correct permission assigned.

legacy code:

```
assertPermisson("doStuff")
doStuff()

if(hasPermission("doMore")) {
    x = doMore()
}
```

new code:

```
checkpoint.perform("doStuff")
x = checkpoint.performSoftfail("doMore")
```

pseudocode of implementation outline of the checkpoint:

```
// all corresponding functions will get an attribute "permission"

class checkpoint {
    init() {
        // register all functions that require a certain permission
        self.modules = map(name, function)
    }

    perform(action) {
        if(user.hasPermission(self.modules[action].permission)) {
            return self.modules[action].call()
        }
        else {
            log()
            throw Unauthorized
        }
    }

    performSoftfail(action) {
        if(user.hasPermission(self.modules[action].permission)) {
            return self.modules[action].call()
        }
        else {
            // possibly allow returning empty array or similar
            return self.modules[action].softfail()
        }
    }
}
```

note: this would probably obsolesce https://github.com/meteor-gazelle/meteor-gazelle/issues/141

**Comment by ghost** [comment]
I'm currently working on an implementation of this, see #115

**Comment by jimrollenhagen** [comment]
It would be reeeeally interesting if we could hook into Meteor.call somehow, and have `Meteor.method` things register permissions and whatnot. But we also need permissions for things to be massively configurable. This might get hard :)

Could also be useful for feature flags, obviously.
