### ISSUE TITLE
Specifications for uploading torrents

### ISSUE THREAD

**Issue by thomwiggers** [meteor-gazelle/meteor-gazelle#146]
Hangs on lots of things right now but in the mean time we can collect some observations here.
- We MUST NOT automatically mark stuff freeleech based on other freeleech torrents.

```
17:53 <lawnmower> ppl uploading stuff to FL groups to get their torrents FL
17:54 <lawnmower> that's something nobody would want
```

**Comment by ghost** [comment]
I've been staying on top of staff to provide specs for uploading, starting with music. Slow progress but we'll get something eventually...
