### ISSUE TITLE
Do we want to lint SCSS code?

### ISSUE THREAD

**Issue by sneakysneakysneaky** [meteor-gazelle/meteor-gazelle#149]
Do we want to add a SCSS Linter? [scss-lint](https://github.com/brigade/scss-lint) has some pretty cool features to enforce BEM & keep the codebase clean. But it would add a rubygem to a JS project :(

@ajax-wcd @Malvar @salas-wcd

**Comment by ghost** [comment]
@sneakysneaky any way to do it without a gem?

**Comment by sneakysneakysneaky** [comment]
@ajax-wcd Not that i've been able to find.

**Comment by ghost** [comment]
@sneakysneaky perhaps it could be an optional dependency which someone who is working on css adds. They are responsible for linting the scss they write? If we can add the linter then can make sure no bad scss is pushed.

**Comment by ghost** [comment]
Add the linter to Travis that is. Sorry mobile typing.

**Comment by salas-wcd** [comment]
And then i may refactor the gem linter to js : i thibk it is a onr week job.

**Comment by ghost** [comment]
We have a linter, it's called a "pull request". I would recommend not using a linter and ensure people use pull requests correctly and enforce BEM or what not through that.

**Comment by ghost** [comment]
Another option to this, if you really feel you need it is to use it within CI like @ajax-wcd mentioned and only lint the output. If the CSS passes linting then you can assume the SCSS is done correctly, other than structural changes, which a linter may/may not pick up.

**Comment by sneakysneakysneaky** [comment]
@ajax-wcd, I agree adding SCSS linting to CI would be ideal. Otherwise, we don't get any benefit. As you say, we could add the rubygem as an optional dependency, and then another argument to run_tests.sh (ie `./run_tests.sh --css-lint-tests` or something).

@belairWCD, the linting rules will have to be awfully lax if we intend to enforce by manually reviewing pull requests alone. Sure, we could catch probably basic BEM violations, but we wouldn't be able to reliably detect poor practices (over-nesting, duplicate rules, etc).

We could lint the compile CSS, i suppose. We wouldn't be able to prevent poor SCSS practices (bad use of placeholders, variables, poor nesting etc). We'd also have to build CSS once for the linter, then again for meteor.

**Comment by ghost** [comment]
> but we wouldn't be able to reliably detect poor practices (over-nesting, duplicate rules, etc).

I completely disagree, over-nesting should be easy to spot and duplicate rules comes down to better organised CSS files. I'm not completely against a linter, I just think that it should never be relied on and more often than not they're pains to get set up.

**Comment by sneakysneakysneaky** [comment]
[This is kinda what i had in mind](https://github.com/sneakysneakysneaky/meteor-gazelle/tree/feature/scss-lint). The linter was super easy to install & configure. I haven't tested CI, obviously.

As i say, my only real objection is that is adds a ruby dependency to a JS stack. That's reason enough to reject this proposal.

**Comment by thomwiggers** [comment]
> As i say, my only real objection is that is adds a ruby dependency to a JS stack. That's reason enough to reject this proposal.

As long as it's not a build or runtime dependency I don't really care. The way you've set that up in the PR is great imo, as it's easily left out of your own process and Travis can really help reviewing in the PR. Of course, it's not a replacement for manual review.

**Comment by sneakysneakysneaky** [comment]
I feel this has gotten enough lukewarm feedback for a formal PR. Please share your thoughts, add recommendations for rules you don't like, etc. Or straight up thumbs-down it. You won't hurt my feelings.

**Comment by ghost** [comment]
@sneakysneakysneaky As long as ruby is a soft dependency, whatever you decide has my stamp of +1

**Comment by ghost** [comment]
Merged #159.
