### ISSUE TITLE
Improvements concerning Top10

### ISSUE THREAD

**Issue by salas-wcd** [meteor-gazelle/meteor-gazelle#158]
The Top10 for torrent aims to provides users trending torrents.
As I stated in #153, there is some better way to compute trending.

Moreover we could think of personalising trending with machine learning (like multilayer perceptron).
Well for music there is lastfm but for more general content their is no such api.

What do you guys thinks of a `meteor-gazelle:trending` based on some neural networks scheme (MLP seems good to me) and some better statistic analysis that can provides some _good for you_ content by default and use general api (like lastfm) if the user set it up ?

**Comment by TheDevKing** [comment]
I don't think personalized trending is appropriate if based on snatches. This is because it seems to presume that everything one snatches is something they had a positive experience with. As most of us are probably aware, a snatch is not the same thing as a vote of satisfaction/enjoyment/approval. This problem could be resolved by having it instead rely on a rating system (which I don't know if anyone's even begun discussing yet).

**Comment by ghost** [comment]
@salas-wcd I think this is scope creep. Furthermore there are plans for a rating system in the distant future, in fact there may even be a placeholder spec issue for it. We need to focus on delivering core functionality.

@TheDevKing +1

**Comment by salas-wcd** [comment]
@TheDevKing I was more thinking of a neural network that takes `[number of snatches, snatches that users also snatches, rating, genre proximity, content author proximity]` that will output a `proximity beetween two torrents` and another neural network that take `the previous torrent proximity`, and the `other torrent snatched, lastfm or rotten-tomatoes artists` and  output a `trending sugestion`. Both will learn to a tinder-ish (like/dislike) back-propagation.

@ajax-wcd yes it is low priority ! But it can be developed in a separate package and included to core once it works. More over the cost of maintenance isn't that hard since the flexibility of neural networks. For instance if one wanna change one input, it would require just add the input in the package conf.  Having such a system can really makes you discover new content better than looking at snatches number or  the staff pick (which remains excellent picks by the way). But yes it is low priority so I will close for now.
