### ISSUE TITLE
Created by and edited by Astronomy behavior

### ISSUE THREAD

**Issue by ghost** [meteor-gazelle/meteor-gazelle#160]
An Astronomy behavior is needed to adds fields for tracking the user who created a document as well as tracking users who have edited a document. 

Research starts here 
https://github.com/jagi/meteor-astronomy/wiki/Behaviors#introduction

**Comment by rhomes-wcd** [comment]
I figured you or I would get this for our dev tasks.

**Comment by ghost** [comment]
@rhomes-wcd Yeah, I'll probably take it but made an issue anyways in case anyone wants to sweep it up before I do,

**Comment by daveynight** [comment]
Before I commit anything, I just want to ask if I've missed the mark here:

``` javascript
Astro.createBehavior({
  name: 'trackAuthors',
  events: {
    addbehavior: function(creator) {
      var Class = this;

      Class.addFields({
        createdBy: {
          type: 'string',
          default: null
        },
        editedBy: {
          type: 'string',
          default: []
        }
      });

      Class.addEvents({
        beforeInsert: function() {
          this.createdBy = Meteor.user().username;
        },
        beforeUpdate: function() {
          this.updatedBy.push(Meteor.user().username);
        }
      })
    }
  }
})
```

_edit_: btw I have that in the `meteor-gazelle-announcements/lib/model.js` file

**Comment by ghost** [comment]
@daveyshindig 

The name of the behavior should be createdBy not trackAuthors.

You should be storing the user's id, not their username (theres a userid function). Consider what happens when a username is changed...

I think that var Class = this should instead be var self = this; or you can just reuse 'this' since you're not referencing it again under a different scope. 

Should createdBy be a required field? I think so...

I would changed editedBy to updatedBy to stay within the same vocabulary. 

Furthermore this should be in its own package.
