### ISSUE TITLE
Glossary of terms

### ISSUE THREAD

**Issue by ghost** [meteor-gazelle/meteor-gazelle#164]
This is a continuation of the work discussed in #142 

Create a generic glossary that we use for content on the site. For example what is the generic name for an 'artist' or 'torrent groups'? 

Malvar started a glossary which can be found [here](https://github.com/meteor-gazelle/meteor-gazelle/compare/doc/glossary) but it's still a WIP and needs more work.

**Comment by TheDevKing** [comment]
I'll do some work on this today and try to cover all the terms that would be necessary for general implementation.

**Comment by ghost** [comment]
@TheDevKing Sounds good, thanks!

**Comment by c-p-b** [comment]
The glossary defined here should be included in #137

**Comment by TheDevKing** [comment]
Not trying to seek arbitrary validation here, but I think it's important to affirmatively know what objections, if any, there are to what I've done so far before continuing. I think authoring the glossary is a huge responsibility that should not be done in isolation, as it is quite literally defining the core components of the project.

I'd really like to know what people think so far to inform how development of this proceeds.

**Comment by c-p-b** [comment]
@TheDevKing please ping !core in #gazelle and reference this issue when adding commits, we will be happy to provide feedback.
