### ISSUE TITLE
Update Astronomy behaviors after timestamp PR is accepted 

### ISSUE THREAD

**Issue by ghost** [meteor-gazelle/meteor-gazelle#165]
Opening this issue to keep track of PR submitted by @jimrollenhagen found [here](https://github.com/jagi/meteor-astronomy-timestamp-behavior/pull/2)

**Comment by jimrollenhagen** [comment]
The author actually ended up implementing it, just need to wait for a release now.

**Comment by rhomes-wcd** [comment]
Awesome
