### ISSUE TITLE
Implement reactive-table

### ISSUE THREAD

**Issue by ghost** [meteor-gazelle/meteor-gazelle#172]
This is a package for paging and filtering on tables. This is useful for pages containing tables backed by a data source, for example a list of ip bans. 

https://github.com/aslagle/reactive-table
http://reactive-table.meteor.com/

@rhomes-wcd Overlaps with #168

**Comment by rhomes-wcd** [comment]
I will take a look into this once I get around to the ban ip CRUD form.

**Comment by sneakysneakysneaky** [comment]
Lets be especially careful with class names & styling. Reactive table seems to lean heavily towards bootstrap.

**Comment by ghost** [comment]
@sneakysneakysneaky Excellent point
