### ISSUE TITLE
Create guidelines for how to structure packages

### ISSUE THREAD

**Issue by ghost** [meteor-gazelle/meteor-gazelle#178]
How should files be named and structured in packages?

Guidelines need to be created. 

I'm of the opinion that for small packages, rather than creating a bunch of different files and folders to just put code into one or two files where it makes sense logically. As a package grows the code can be broken up into more files.

**Comment by sneakysneakysneaky** [comment]
My 2 cents.
- package-name
  - README.md
  - package.js
  - lib/ (or both/, but lib/ seems to take precedence)
  - client/
  - server/
  - tests/
  - assets/

**Comment by ghost** [comment]
@sneakysneakysneaky +1

**Comment by jimrollenhagen** [comment]
Maybe add `templates/` to that, where needed? LGTM though

**Comment by saintsaens** [comment]
I've read somewhere of public/ for all things public, and collections/ at the root for stuff dealing with elements in the DB.
