### ISSUE TITLE
Create a basic Wiki

### ISSUE THREAD

**Issue by ghost** [meteor-gazelle/meteor-gazelle#182]
The specs can be found here: https://github.com/meteor-gazelle/meteor-gazelle/blob/master/doc/specs/wiki.md

A couple thoughts,
1. Depends on classes and permissions which will are still being worked on.
2. Managing a revision history on a document is a package which would be beneficial here, an issue already exists for it #116
3. We should strive to make this wiki generic and publish it as a package as no basic wiki package exists for Meteor yet.

**Comment by daveynight** [comment]
I'm currently working on this, keeping @ajax-wcd's above comments in mind. I'll work to keep the package uncoupled from our project, to publish the wiki separately. I have 4hrs/day to spend on this (it's a means for me to learn and practice Meteor), so hopefully with a little guidance from the team I'll be able to get the hang of Meteor and check in a high quality project before too long.
