### ISSUE TITLE
Consider Switching to Semantic UI

### ISSUE THREAD

**Issue by sneakysneakysneaky** [meteor-gazelle/meteor-gazelle#184]
Consider switching the stylesheet framework to [Semantic UI](http://semantic-ui.com/). @ajax-wcd @Malvar 

**Pros**
- Accessible. Easy for non-stylesheet developers to use.
- Plays well with meteor. (Better than the current NPM / Bourbon solution, anyway.)
- Well-documented, good-looking styles. Anyone familiar with Bootstrap or Foundation should feel right at home.
- Written in LESS.
- Framework is easy to optimize to include only the desired elements.
- Themable. Every third-party Gazelle stylesheet could also use Semantic UI.

**Cons**
- Current SCSS code will need to be ported to LESS.
- [LESS stylesheets & themes are not well documented.](https://github.com/Semantic-Org/Semantic-UI-LESS) When creating a theme, it's not immediately clear what the variables are or what they do. Lots of reverse engineering will be needed.
- Will create semantic issues. Grids are the chief offender. 
  - See [this article](https://www.ostraining.com/blog/coding/bootstrap-right-way/) for a more in depth description of the problem; is about Bootstrap, but the same applies. Except ironically, Semantic UI's mixins are poorly documented & appear weaker than Bootstrap's.
  - The severity of this problem will depend on the scope of a third-party stylesheet. See #126.
- The framework is simplistic. [Mockups](https://trello-attachments.s3.amazonaws.com/55bbafd3ebb18834c04ecf9b/600x1615/b447ed81303aa516abb0dccd85f3d533/mockup-1.jpg) are complex. Will need a lot of custom development anyway, & Semantic may not save us any time.

**And now the opinionated stuff**
- Moves animations from the stylesheet to jQuery, which is step backwards & will complicate third-party stylesheets.
- More complaints on semantics & separation of responsibilities. The markup, stylesheets, & scripts are all responsible for styling. This will become very hard to manage, especially with such a diverse team.
  
  I am not a fan of the pattern below. Like most CSS frameworks, **the class names don't describe what each element _is_ but rather what it _looks like_.** This pattern does not separate responsibilities, scales poorly, & will be problematic when third-party stylesheets want to make different choices. 
  
  ``` html
  <div class="ui grid">
    <div class="twelve wide column"></div>
    <div class="four wide column"></div>
  </div>
  ```
  
  I am much more in favor of this pattern. Like what is provided by [Neat](http://neat.bourbon.io/) or [Susy](http://susy.oddbird.net/). In this pattern, the stylesheet is responsible for the styles while the markup is responsible for structure & content.
  
  ``` scss
  .container { @include grid; }
  .main { @include col(12); }
  .sidebar { @include col(4); }
  ```
  
  ``` html
  <div class="container">
    <div class="main"></div>
    <div class="sidebar"></div>
  </div>
  ```
  
  JavaScript should only be used for styling when it's the only option (example: calculated positioning, complex animations, etc).

**Comment by Malvar** [comment]
I'm against this recommendation completely.
- Using design and UX semantics 1:1 with markup will handcuff theme modulation and creativity.
- Relying on a semantic description for a style will immediately neuter existing stylesheets when a UX or design change is implemented that requires a change to the semantic classes used.

I realize that the reason for this proposal is to make the markup more readable, and the UX intention more understandable, but perhaps there is a better solution to this problem.

**Comment by ghost** [comment]
Thanks for the research, closing this issue as we'll be sticking with Bourbon and friends,.
