### ISSUE TITLE
Add meteor-typeahead package

### ISSUE THREAD

**Issue by ghost** [meteor-gazelle/meteor-gazelle#188]
We need to add a typeahead package which would be used on forms throughout the site. 

https://github.com/sergeyt/meteor-typeahead/
https://github.com/mizzao/meteor-autocomplete/

**Comment by salas-wcd** [comment]
Doesn't it rely on twbs:boostrap meteor package ??
Others possibilities:
- https://github.com/mizzao/meteor-autocomplete/

**Comment by Malvar** [comment]
+1 to meteor-autocomplete if we want to be able to autocomplete from multiple different collections...which I think we do.

**Comment by tonytamps** [comment]
I don't think this can be done yet. We need the search facility and torrent lists working properly first.

**Comment by ghost** [comment]
@tonytamps There's other kinds of data that this would be used for, such as tags. 

@salas-wcd @Malvar That autocomplete package is another option, they both need to be looked into.
