### ISSUE TITLE
Move to Velocity testing framework

### ISSUE THREAD

**Issue by rhomes-wcd** [meteor-gazelle/meteor-gazelle#189]
The Velocity testing framework is the de facto standard to testing Meteor applications. We need to rewrite our current tests, documentation, and CI commands to utilize this framework.

https://velocity.readme.io/

**Comment by salas-wcd** [comment]
Bis +1 for this !

**Comment by jimrollenhagen** [comment]
What's the reason we didn't go with this in the first place? More out of curiousity than anything.

**Comment by ghost** [comment]
@jimrollenhagen meteor packages use tiny test by default so we stuck with that.

**Comment by rhomes-wcd** [comment]
Just fyi Im working on the refactor right now. PR will be sent later today.
