### ISSUE TITLE
ECMA 2015

### ISSUE THREAD

**Issue by salas-wcd** [meteor-gazelle/meteor-gazelle#191]
Meteor released Es6 compatible version (http://info.meteor.com/blog/announcing-meteor-1.2) !
We shall make the transition to it !

**Comment by salas-wcd** [comment]
Should I make a PR ??

**Comment by ghost** [comment]
@salas-wcd, I am handling this, no need to create a pr.

**Comment by salas-wcd** [comment]
Oki thought i could help a bit on this.
