### ISSUE TITLE
"no route on the client or the server"

### ISSUE THREAD

**Issue by k0nsl** [meteor-gazelle/meteor-gazelle#201]
I'm pulling latest code from the repo and installed on Ubuntu 14.04.3.

Meteor 1.2.1
NodeJS: 5.3.0

I get the application up and running fine and I can create a user. However, upon logging in and trying to access any URL in the menu, doesn't matter which one, I'm constantly receiving this message:

```
Oops, looks like there's no route on the client or the server for url: "http://localhost:3000/rules."
```

Any ideas as to why this occurs?

Merry Christmas!

**Comment by sneakysneakysneaky** [comment]
This project is still in very early stages. Virtually no routes are in place. Stay tuned for more updates.
