### ISSUE TITLE
Artists Specs

### ISSUE THREAD

**Issue by ghost** [meteor-gazelle/meteor-gazelle#23]

**Comment by seanvandermolen** [comment]
There should be some procedure for disambiguation.  Not only in search results but for cleaning up current artist pages with torrents from 2 or more artists with the same or similar names.  Also when artists have spelled their names differently or have had many aliases the system should be able to deal with those issues.

**Comment by sneakysneakysneaky** [comment]
The term "artists" is very specific to music. Since this project is a framework, should this be more generic? Make taxonomies configurable?

**Comment by ghost** [comment]
@sneakysneakysneaky Yes it should be. "Content creator" was thrown around as an alternative. We should try to stay as generic as possible.

**Comment by ghost** [comment]
@ajax-wcd and @sneakysneakysneaky Perhaps the term contributor would be most generic. This means that for applications that are hosted the producing company would be considered the primary contributor whereas with music the contributor is specifically an artist. I want to start tackling this spec but I think it will be difficult until we actually have a solid decision about this because I think it affects the spec at a core level.

**Comment by thomwiggers** [comment]
I think we need an even more generic meta-model in which you can create these relationships. Otherwise there's no way we're going to get this flexible enough.

Eg. books are similarly related to music, but movies or software not so much. 

We need something like groups can contain torrents, or other groups?

**Comment by thomwiggers** [comment]
I've created #137 for this.
