### ISSUE TITLE
User Settings Specs

### ISSUE THREAD

**Issue by ghost** [meteor-gazelle/meteor-gazelle#63]

**Comment by ghost** [comment]
Going to move forward with the latest version made by tonytamps. Wasn't sure how to get info from his fork, so I made my own branch on my fork but he is still an author on the metadata of my version. I will be adding myself as an author as well.

**Comment by tonytamps** [comment]
Let me get home and I'll contact you on IRC.

**Comment by ghost** [comment]
Sounds good. Talk to you soon. :)
