### ISSUE TITLE
Update docker scripts

### ISSUE THREAD

**Issue by ghost** [meteor-gazelle/meteor-gazelle#72]
Update the docker scripts since they are out of date

**Comment by jimrollenhagen** [comment]
Killed with fire in #104

**Comment by n1889** [comment]
Could it be an idea to add these tests as pre-commit / pre-push hooks for git to ensure tests are being run, and passing?

Edit: PR https://github.com/meteor-gazelle/meteor-gazelle/pull/112 opened to add this

**Comment by jimrollenhagen** [comment]
I swear I closed this last night... will discuss the PR in the PR
