### ISSUE TITLE
Create github pages

### ISSUE THREAD

**Issue by ghost** [meteor-gazelle/meteor-gazelle#73]
Create a landing page for meteor-gazelle using github pages.

**Comment by jrherr** [comment]
I'll take this -- I can't add a `gh-pages` branch with a pull request, so someone will have to create a empty `gh-pages` branch so I can add the landing page with my pull request. 

I've [already started a rough draft](http://jrherr.github.io/meteor-gazelle/) in [my fork of the repo](https://github.com/jrherr/meteor-gazelle).  

I'm also not familiar with the project a ton, so I've kept it minimal, but any feedback would be greatly appreciated (i.e. how many things should be on the public page and what the consensus of the aesthetics should be).

**Comment by ghost** [comment]
@jrherr I've pushed a gh-pages branch for you.

**Comment by jrherr** [comment]
@guitarman0831 Great!  I'll send a pull request now.  I'm warning you -- it's a quick draft in just a few minutes, but it's a starting template.

**Comment by ghost** [comment]
@jrherr Left some comments then I saw this discussion and realized they would been more at home here.

Firstly, this is what the old page looked like, may serve as inspiration, http://whatcd.github.io/Gazelle/

Secondly, we should decide what sort of information should be on this page. Ideas?

**Comment by thomwiggers** [comment]
Suggestions for content:
- [ ] How to get started-guide
- [ ] Links/include `CONTRIBUTING.md`
- [ ] More detailed 'this is how we do things' for eg. writing specifications, writing features
- [ ] some meta-stuff like what do the labels mean
- [ ] who task what questions on the core team

**Comment by jrherr** [comment]
Thanks!  This all sounds great to me.  I threw the landing page up kinda quick, but I'll have some time later to go over it.

**Comment by jrherr** [comment]
I've updated my gh-pages fork to incorporate some of the changes above.  I've included a folder with old-ish WCD meteor wiki md files -- these will need some updating.  

Should we have a github wiki or do you want all the information to be on pages off the landing page? Both?

**Comment by ghost** [comment]
@jrherr @thomwiggers Both these comments and list of changes/must-haves should be placed into a PR for this work IMO and refrence it here.

**Comment by jrherr** [comment]
@belairWCD Sure, [here's the original PR](https://github.com/meteor-gazelle/meteor-gazelle/pull/87) which now includes the changes I made over the weekend.  

I'm not sure how to proceed and what else needs to be included in the landing page (should we duplicate the "wiki" via other pages off the landing page or just one page to direct interested peoples) and how much to subtly communicate.  

Any comments on the PR code would be appreciated.  Thanks everyone for your input!

**Comment by ghost** [comment]
@jrherr My vote is for a single page to keep it simple.

**Comment by ghost** [comment]
This page needs to be updated with up to date information.
