### ISSUE TITLE
Create a logo for the project

### ISSUE THREAD

**Issue by ghost** [meteor-gazelle/meteor-gazelle#86]
The project currently uses Github's gravatar for a logo, we need a real one.

**Comment by coldkick** [comment]
Figuring out how to integrate the meteor aspect is difficult, I feel it should have to do with the eyes. Thoughts?

![](http://i.imgur.com/Sxgqmop.png)

**Comment by ghost** [comment]
Looks good. Perhaps the eyes could be a bunch of stars? 

Google galaxy effect

**Comment by ahaym** [comment]
is there any reason we can't have the icon as a gazelle from a side perspective? if we did this, it'd be much easier to integrate the "meteor" aspect into the logo. Here's a mockup I made from some clipart; someone with more graphic design experience would be better equipped to explore this further.

![untitled](https://cloud.githubusercontent.com/assets/11877361/9071091/29127e86-3aa8-11e5-9cc5-8c9bbf99ad62.png)

**Comment by thomwiggers** [comment]
I'd be hesitant with basing this on any clip art that's not licenced with Creative Commons licences (not the ND variants) or even more free licences.

**Comment by ahaym** [comment]
@thomwiggers: I didn't mean to propose that as a logo, sorry. As I cannot draw, I meant to post that simply as a mock-up to what a logo could look like. The idea would be a gazelle in a leaping motion with meteor trails around it.

**Comment by thomwiggers** [comment]
No worries. I'm not a copyright lawyer, but I just think we need to be fairly careful about these things :smiley:

**Comment by Malvar** [comment]
How about something much simpler...

![meteor-gazelle-logo](https://cloud.githubusercontent.com/assets/13203844/9075765/dc478ec2-3ae6-11e5-96d6-499c94d9c927.png)

**Comment by sneakysneakysneaky** [comment]
Meteor may have a problem with us adapting their logo. (I am also not a copyright lawyer.)

**Comment by Malvar** [comment]
Some other options I was playing with this morning. Share likes and dislikes.

![meteor-gazelle-logo-options_01](https://cloud.githubusercontent.com/assets/13203844/9086288/8886512c-3b51-11e5-8b4f-08f67adfbbc3.png)

**Comment by ghost** [comment]
+1 on @coldkick's logo. However, I would like to see a version with the galaxy eyes, as @ajax-wcd had mentioned.

**Comment by coldkick** [comment]
From @Malvar I like the top right with the horizontal 'horns' the most. It has the best balance. I can do a galaxy eyes change today, that's no problem!

**Comment by coldkick** [comment]
@ajax-wcd @guitarman0831 

![](http://i.imgur.com/6QXA6zd.png)

**Comment by ghost** [comment]
That looks sick. +1

**Comment by thomwiggers** [comment]
https://www.youtube.com/watch?v=MAW2lygZC_4

**Comment by ghost** [comment]
@coldkick Looks great.

@Malvar I like the top right as well.

**Comment by c-p-b** [comment]
I like Malvar's top right Gazelle logo as the horns can convincingly be construed as meteor tails and vice versa (I assume that was the intention).

**Comment by ghost** [comment]
@Malvar I like the top right logo,

@coldkick I think I like the one with the galaxy stars a ton! :)

**Comment by ghost** [comment]
Do you guys think we could use utilize both logos but in different places?

**Comment by coldkick** [comment]
@Malvars design would be great for the header of the default template. While I'd say mine is more geared towards larger presentation such as t-shirts, stickers, merch stuff.

**Comment by ghost** [comment]
@coldkick In that case I think you and @Malvar should coordinate for colors and maybe the horns?

**Comment by ghost** [comment]
My vote is using @Malvar's for the project logo, and @coldkick's for merch. That would look awesome on a tshirt or coffee mug.

**Comment by rhomes-wcd** [comment]
+1 for @Malvar's top right for project logo, @coldkick's for merch as well.

**Comment by ghost** [comment]
Hey @Malvar and @coldkick any updates on this?

**Comment by coldkick** [comment]
I've been busy with a new work project that's been taking my time. I'll see if @Malvar  can send me the horns as an svg so we can make them match.

**Comment by Malvar** [comment]
@coldkick 
Here are the horns.

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
     viewBox="0 0 108.041626 55.2815285" enable-background="new 0 0 108.041626 55.2815285" xml:space="preserve">
<g>
    <path fill="#DC534C" d="M103.2591019,44.375679c0,0-23.0221405-10.1669846-52.692749,3.4883461
        C37.1072159,54.0583801,21.828989,53.9518623,0,49.206646c0,0,26.1545067,11.6571007,52.8318405,2.6754456
        c24.9998703-8.4168854,46.3252945,2.5444069,46.3252945,2.5444069s5.2653351,2.1248665,7.6058731-2.9052849
        C109.1035919,46.4911003,103.2591019,44.375679,103.2591019,44.375679z"/>
    <path d="M106.3366013,45.7954445c0,0-15.2152863-20.0469818-47.7870827-22.4741917
        C43.7743301,22.2202625,30.4600716,14.7258615,13.6621275,0c0,0,17.2337189,22.8679943,44.9228401,27.9338474
        c25.9480362,4.7473164,39.2941971,24.6672497,39.2941971,24.6672497s3.5769272,4.4095802,8.0612488,1.1428757
        C110.4247665,50.4773216,106.3366013,45.7954445,106.3366013,45.7954445z"/>
</g>
</svg>
```

**Comment by ghost** [comment]
@coldkick Hey could you please provide the svg for the logo?
