### ISSUE TITLE
What about using react

### ISSUE THREAD

**Issue by salas-wcd** [meteor-gazelle/meteor-gazelle#94]
Hi guys:

I was so impressed to see this new project on WCD home page.
Since you are already using a js based solution what about using React as the view layer ?

React can be tightly integrated to meteor (see http://info.meteor.com/blog/meteor-the-missing-infrastructure-for-building-great-react-apps).

The benefits will be:
- making some reusable components
- easily debugable as pure function
- easy to make an native (IOS now or android in a few month)  with reusing more than 80% of existing code

Personally, I used react a lot (and love it), I tried meteor some times ago but don't invest so much time in. BUt some friends made the transition from blaze to react and they were all happy with.

WDYT guys ??
I can pull request if you guys interested.

**Comment by salas-wcd** [comment]
Nevermind,  after reading the all thread on what,  after eating some popcorn for all "meteor sukkks",  "lets rewrite in django"  or even "... in haskell",  i found the answer that your waiting till meteor 1.2 for having the official integration of react. 

I won't wait that long without doing anything so except some spec inc...

**Comment by ghost** [comment]
Sounds good. 

Restating here for more context

Although we're not using the Flux and React architecture with Meteor, it is indeed possible. For example [space-ui](https://github.com/CodeAdventure/space-ui) is package which does so. Earlier on I was looking into the possibility of using React with Meteor, the two go together quite well in theory, but ultimately decided to wait until it's [officially](http://info.meteor.com/blog/whats-coming-in-meteor-12-and-beyond]supported in 1.2) to investigate it fully. Also as a side note, using [reluxjs](url=https://github.com/reflux/refluxjs) in a typical node stack was looked into and prototyped for some time before settling on the Meteor stack.

Closing issue.

**Comment by salas-wcd** [comment]
I also have started some times ago a rewrite of gazelle and get the same choice.
I think the choice of meteor is a good choice for now since react and flux ecosystem is changing too fast.

What concern me at most is the use of mongo as a db. Get some problem in scalling due to bad sharding design and so on. But I also have heard they have improved a lot.

**Comment by salas-wcd** [comment]
@ajax-wcd, please reopen the react issue since meteor 1.2 natively supports it.
Pros:
- force us to build the UI as as tree of reusable components
- stateless components are simple arrow function that makes way lighter it was before
- there is a bunch of developer tools that we can enable
  Cons:
- yet another thing to learn
- im not sure if it is possible to use it only where it can be helpfull

WDYT

**Comment by ghost** [comment]
I've done extensive research into this already, we will be sticking with blaze.

React has a lot of benefits but it's still relatively new in the meteor ecosystem. Using react would paint us into a corner for when it comes to using other packages since the majority would use blaze. Case in point is the user accounts package, it does not have react support yet which throws a monkey wrench into our authentication pages. 

React is great and I would use it for other projects but in the case of gazelle, we should stick with the lowest common denominator for the sake of simplicity and development speed.

**Comment by salas-wcd** [comment]
More over react is great to re factor existing system with so we can switch later on if needed.
I completely agree with you.

**Comment by salas-wcd** [comment]
@ajax-wcd : I see some work done in react. Is this something I can help (im proficient in) or you are handling this alone ??

Can you (or I open a pull request) so i can comment in
